sudo: true
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt install font-manager
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run -a realtime_test.py
  - coverage run -a simulate_test.py
  - coverage run -a utils_test.py
after_success:
  - codecov