sudo: false
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run realtime_test.py
  - coverage run simulate_test.py
  - coverage run utils_test.py
after_success:
  - codecov